{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gaia-daemon.fullname" . }}
  labels:
{{ include "gaia-daemon.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["deployments"]
  resourceNames: ["{{ include "gaia-daemon.fullname" . }}"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "watch", "list"]
{{- end -}}
